### ISSUE TITLE
Default Key Bindings

### ISSUE THREAD

**Issue by shivanan** [mlewand/vscode-selection-flip#1]
Thanks for writing this extension. I was going to do my own that does the exact same thing, assuming nothing existed to do it, and then I found this.

Only complaint: On macOs the Alt+I binding doesn't seem to work for whatever reason - may be switch the default binding on Mac to something else?

**Comment by mlewand** [comment]
Sure, I'm fine with changing the default hotkey for that command on Mac. Do you have any propositions as far as the hotkey goes?

Though it's weird that `alt+i` doesn't work by default 🤔

**Comment by jpotterm** [comment]
The reason it doesn't work on macOS is because Alt is a system-wide command to enter alternate symbols: https://en.wikipedia.org/wiki/Alt_key#macOS. So on macOS `Alt+i` enters characters like this: âêû. I've been using `Cmd+i` instead and it seems to work well.

It's not a big deal because it's easy to set up the custom keybinding, but it would be nice to have the default one work out of the box on macOS.

By the way, thanks for the useful and simple extension!

**Comment by mlewand** [comment]
Thanks both of you for the input. Also thanks @jpotterm clarifying this ❤ (Unfortunately!) I've been out from vscode extensions development for a little while. But I'll try to put a fix for this issue. `cmd+i` sounds like a nice alternative for macOS.

If the release process of vscode didn't change too much I should be able to release it this weekend.

**Comment by mlewand** [comment]
Well, fixing this was easy. Getting CI back on track was easy.

But ofc the most difficult part would be the actual release or more precisely: signing into Microsoft account 😅 I forgot the password and it's virtually impossible to reset it. Each time I have to use MS credential, I always end up with tons of trouble.

Anyway I'll give it a try the other day.

**Comment by mlewand** [comment]
Ok, who am I kidding. I couldn't stop from poking and trying my old emails, finally got it working. New version published on the [marketplace](https://marketplace.visualstudio.com/items?itemName=mlewand.vscode-selection-flip), enjoy!

**Comment by jpotterm** [comment]
Thanks @mlewand that was super fast! I tested it out on macOS and it's working great for me!
